source.. = src/main/java/,\
           src/test/java/
bin.includes = META-INF/,\
               .,\
               lib/jersey/asm-3.1.jar,\
               lib/jersey/jackson-core-asl-1.9.2.jar,\
               lib/jersey/jackson-jaxrs-1.9.2.jar,\
               lib/jersey/jackson-mapper-asl-1.9.2.jar,\
               lib/jersey/jackson-xc-1.9.2.jar,\
               lib/jersey/jersey-bundle-1.17.jar,\
               lib/jersey/jersey-multipart-1.17.jar,\
               lib/jersey/jettison-1.1.jar,\
               about.html
project.name = tech.laces.ldp
lib.dir = lib
src.dir = src/main/java
build.dir = build
dist.dir = target
project.manifest = META-INF/MANIFEST.MF
 
