output.. = bin/
bin.includes = META-INF/,\
               plugin.xml,\
               .,\
               icons/,\
               about.html
source.. = src/main/java/
bin.excludes = **/_svn/*,\
			   **/_svn/**
			   
