bin.includes = META-INF/,\
               apache-jena-2.11.0/lib/commons-codec-1.6.jar,\
               apache-jena-2.11.0/lib/httpclient-4.2.3.jar,\
               apache-jena-2.11.0/lib/httpcore-4.2.2.jar,\
               apache-jena-2.11.0/lib/jena-arq-2.11.0.jar,\
               apache-jena-2.11.0/lib/jena-core-2.11.0.jar,\
               apache-jena-2.11.0/lib/jena-iri-1.0.0.jar,\
               apache-jena-2.11.0/lib/jena-sdb-1.4.0.jar,\
               apache-jena-2.11.0/lib/jena-tdb-1.0.0.jar,\
               apache-jena-2.11.0/lib/log4j-1.2.16.jar,\
               apache-jena-2.11.0/lib/xercesImpl-2.7.1.jar,\
               .,\
               src/main/resources/log4j.properties,\
               lib/junit-4.9/junit-4.9.jar,\
               apache-jena-2.11.0/lib/slf4j-log4j12-1.6.4.jar,\
               apache-jena-2.11.0/lib/slf4j-api-1.6.4.jar,\
               lib/nekohtml-1.9.21/lib/bcel-5.2.jar,\
               lib/nekohtml-1.9.21/nekohtml.jar,\
               lib/semargl/semargl-core-0.6.1.jar,\
               lib/semargl/semargl-jena-0.6.1.jar,\
               lib/semargl/semargl-rdf-0.6.1.jar,\
               lib/semargl/semargl-rdfa-0.6.1.jar,\
               lib/semargl/serializer-2.7.1.jar,\
               about.html,\
               log4j.properties
bin.excludes = **/_svn/*,\
               **/svn/**,\
              target/*,\
              target/**
source.. = src/main/java/,\
           src/main/resources/
src.dir = src/main/java
lib.dir = lib
project.manifest = META-INF/MANIFEST.MF
build.dir = build
dist.dir = target
lib.jena.2.11 = apache-jena-2.11.0/lib
lib.jena.2.6 = jena-2.6.4/lib
src.includes = src/main/resources/log4j.properties
src.excludes = src/test/java/,\
               src/test/resources/
