output.. = bin/
bin.includes = META-INF/,\
               .,\
               about.html,\
               plugin.xml,\
               icons/
source.. = src/main/java/,\
           src/test/java/
bin.excludes = **/_svn/*,\
               **/_svn/**
