source.cryptography.jar = src/main/java/,\
                          src/test/java/
bin.includes = META-INF/,\
               lib/bouncycastle/bcprov-jdk15on-149.jar,\
               cryptography.jar,\
               lib/bouncycastle/LICENSE.txt,\
               about_files/,\
               about.html
src.excludes = src/test/java/
