bin.includes = META-INF/,\
               .,\
               about.html,\
               lib/apache/commons-codec-1.3.jar,\
               lib/apache/commons-httpclient-3.1.jar,\
               lib/openrdf/openrdf-sesame-2.6.8-onejar.jar
bin.excludes = **/_svn/*,\
               **/_svn/**,\
               target/*,\
               target/**
source.. = src/main/java/
src.excludes = src/test/resources/,\
               src/main/resources/,\
               src/test/java/
