source.. = src/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               plugin.properties,\
               splash.bmp,\
               plugin_customization.ini,\
               about.ini,\
               about.html
bin.excludes = **/_svn/*,\
               **/_svn/**
src.includes = icons/,\
               splash.bmp,\
               plugin_customization.ini,\
               about.ini
customBuildCallbacks = buildCustomization.xml
