output.. = bin/
bin.includes = META-INF/,\
               plugin.xml,\
               icons/,\
               src/main/resources/rules/,\
               .,\
               about.html,\
               src/main/resources/html/,\
               src/main/resources/introContent.xml,\
               src/main/resources/log4j.properties,\
               semmweb.log4j.properties,\
               src/main/resources/images/,\
               src/main/resources/models/
bin.excludes = **/_svn/*,\
               **/_svn/**
source.. = src/main/java/
src.excludes = src/test/java/
customBuildCallbacks = buildCustomization.xml
customBuildCallbacks.inheritall=true
