#The name of the file doesn't conform to the standard log4j file naming to avoid 
#conflict with the log4j.properties files inside the test folders
#Even though the priority of the rootLogger is set to TRACE the considered priority 
#will be the one specified on each Appender with the Threshold parameter. If you don't 
#specify the priority TRACE here, it will be ignored also in the Appender.
log4j.rootLogger = DEBUG, fileAppender, consoleAppender

# Console Appender
log4j.appender.consoleAppender = org.apache.log4j.ConsoleAppender
log4j.appender.consoleAppender.layout = org.apache.log4j.PatternLayout
log4j.appender.consoleAppender.layout.ConversionPattern = %d{HH:mm:ss,SSS} [%t] %-5p %c.%M - %m%n
log4j.appender.consoleAppender.Threshold=DEBUG

# File Appender, the file is changed at runtime by the CorePlugin
log4j.appender.fileAppender = org.apache.log4j.RollingFileAppender
log4j.appender.fileAppender.File = log/semmweb.log
log4j.appender.fileAppender.MaxFileSize = 5MB
log4j.appender.fileAppender.MaxBackupIndex = 1
log4j.appender.fileAppender.layout = org.apache.log4j.PatternLayout
log4j.appender.fileAppender.layout.ConversionPattern = %d{dd-MM-yyyy HH:mm:ss,SSS} [%t] %-5p %c.%M - %m%n
log4j.appender.fileAppender.Threshold=INFO

# Disable Apache and Jena loggers
log4j.logger.com.hp.hpl.jena.arq.info=OFF
log4j.logger.com.hp.hpl.jena.arq.exec=OFF
log4j.logger.com.hp.hpl.jena=OFF
log4j.logger.org.apache.jena=OFF
log4j.logger.org.apache.http=OFF