output.. = bin/
bin.includes = META-INF/,\
               plugin.xml,\
               .,\
               about.html,\
               icons/,\
               src/main/resources/models/*.ttl.enc
source.. = src/main/java/
bin.excludes = **/_svn/*,\
               **/_svn/**,\
               src/main/resources/models/*.ttl
			   