source.. = src/main/java/,\
           src/main/resources/
bin.includes = META-INF/,\
               .,\
               about.html,\
               lib/spin-1.3.1/spin-1.3.1.jar,\
               src/main/resources/models/
src.excludes = src/test/java/
