source.. = src/main/java/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               about.html,\
               src/main/java/com/semmtech/plugin/semmweb/laces/ldp/model/,\
               src/main/java/com/semmtech/plugin/semmweb/laces/ldp/perspectives/,\
               src/main/java/com/semmtech/plugin/semmweb/laces/ldp/preferences/,\
               src/main/java/com/semmtech/plugin/semmweb/laces/ldp/views/,\
               src/main/java/com/semmtech/plugin/semmweb/laces/ldp/wizards/
bin.excludes = **/_svn/*,\
               **/_svn/**
