source.. = src/main/java/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               about.html,\
               icons/,\
               lib/,\
               src/,\
               plugin.xml
bin.excludes = **/_svn/*,\
               **/_svn/**
jars.compile.order = .
